apiVersion: v1
kind: Namespace
metadata:
  name: fiat-to-usdc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fiat-to-usdc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          ports:
            - containerPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fiat-to-usdc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:latest
          ports:
            - containerPort: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasury-service
  namespace: fiat-to-usdc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: treasury-service
  template:
    metadata:
      labels:
        app: treasury-service
    spec:
      containers:
        - name: treasury-service
          image: treasury-service:latest
          ports:
            - containerPort: 3002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: fiat-to-usdc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
        - name: monitoring-service
          image: monitoring-service:latest
          ports:
            - containerPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: fiat-to-usdc
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: fiat-to-usdc
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: treasury-service
  namespace: fiat-to-usdc
spec:
  selector:
    app: treasury-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: fiat-to-usdc
spec:
  selector:
    app: monitoring-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
